# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ir_events_pb2 as ir__events__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ir_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IREventStreamStub(object):
    """Service definition for streaming IR events
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.unary_stream(
                '/ir.IREventStream/StreamEvents',
                request_serializer=ir__events__pb2.MonitorFileRequest.SerializeToString,
                response_deserializer=ir__events__pb2.IREvent.FromString,
                _registered_method=True)
        self.SendEventBatch = channel.stream_unary(
                '/ir.IREventStream/SendEventBatch',
                request_serializer=ir__events__pb2.IREvent.SerializeToString,
                response_deserializer=ir__events__pb2.MonitorFileResponse.FromString,
                _registered_method=True)


class IREventStreamServicer(object):
    """Service definition for streaming IR events
    """

    def StreamEvents(self, request, context):
        """Start monitoring a file and stream events as they occur
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEventBatch(self, request_iterator, context):
        """Send a batch of events (for testing or batch processing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IREventStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=ir__events__pb2.MonitorFileRequest.FromString,
                    response_serializer=ir__events__pb2.IREvent.SerializeToString,
            ),
            'SendEventBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.SendEventBatch,
                    request_deserializer=ir__events__pb2.IREvent.FromString,
                    response_serializer=ir__events__pb2.MonitorFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ir.IREventStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ir.IREventStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IREventStream(object):
    """Service definition for streaming IR events
    """

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ir.IREventStream/StreamEvents',
            ir__events__pb2.MonitorFileRequest.SerializeToString,
            ir__events__pb2.IREvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEventBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ir.IREventStream/SendEventBatch',
            ir__events__pb2.IREvent.SerializeToString,
            ir__events__pb2.MonitorFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
