# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import analysis_pb2 as analysis_pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """── Service ────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeadCode = channel.unary_unary(
                '/analysis.AnalysisService/GetDeadCode',
                request_serializer=analysis_pb2.FileRequest.SerializeToString,
                response_deserializer=analysis_pb2.DeadCodeResponse.FromString,
                _registered_method=True)
        self.GetCallGraph = channel.unary_unary(
                '/analysis.AnalysisService/GetCallGraph',
                request_serializer=analysis_pb2.FileRequest.SerializeToString,
                response_deserializer=analysis_pb2.CallGraphResponse.FromString,
                _registered_method=True)
        self.GetDependencies = channel.unary_unary(
                '/analysis.AnalysisService/GetDependencies',
                request_serializer=analysis_pb2.FileRequest.SerializeToString,
                response_deserializer=analysis_pb2.DependencyResponse.FromString,
                _registered_method=True)
        self.GetImpact = channel.unary_unary(
                '/analysis.AnalysisService/GetImpact',
                request_serializer=analysis_pb2.ImpactRequest.SerializeToString,
                response_deserializer=analysis_pb2.ImpactResponse.FromString,
                _registered_method=True)
        self.GetFullAnalysis = channel.unary_unary(
                '/analysis.AnalysisService/GetFullAnalysis',
                request_serializer=analysis_pb2.EmptyRequest.SerializeToString,
                response_deserializer=analysis_pb2.FullAnalysisResponse.FromString,
                _registered_method=True)
        self.GetTrackedFiles = channel.unary_unary(
                '/analysis.AnalysisService/GetTrackedFiles',
                request_serializer=analysis_pb2.EmptyRequest.SerializeToString,
                response_deserializer=analysis_pb2.TrackedFilesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/analysis.AnalysisService/HealthCheck',
                request_serializer=analysis_pb2.EmptyRequest.SerializeToString,
                response_deserializer=analysis_pb2.HealthResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """── Service ────────────────────────────────────────────────────────────────

    """

    def GetDeadCode(self, request, context):
        """File-scoped
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDependencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImpact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullAnalysis(self, request, context):
        """Codebase-scoped
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrackedFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Utility
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeadCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeadCode,
                    request_deserializer=analysis__pb2.FileRequest.FromString,
                    response_serializer=analysis__pb2.DeadCodeResponse.SerializeToString,
            ),
            'GetCallGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallGraph,
                    request_deserializer=analysis__pb2.FileRequest.FromString,
                    response_serializer=analysis__pb2.CallGraphResponse.SerializeToString,
            ),
            'GetDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDependencies,
                    request_deserializer=analysis__pb2.FileRequest.FromString,
                    response_serializer=analysis__pb2.DependencyResponse.SerializeToString,
            ),
            'GetImpact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImpact,
                    request_deserializer=analysis__pb2.ImpactRequest.FromString,
                    response_serializer=analysis__pb2.ImpactResponse.SerializeToString,
            ),
            'GetFullAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullAnalysis,
                    request_deserializer=analysis__pb2.EmptyRequest.FromString,
                    response_serializer=analysis__pb2.FullAnalysisResponse.SerializeToString,
            ),
            'GetTrackedFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrackedFiles,
                    request_deserializer=analysis__pb2.EmptyRequest.FromString,
                    response_serializer=analysis__pb2.TrackedFilesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=analysis__pb2.EmptyRequest.FromString,
                    response_serializer=analysis__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """── Service ────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetDeadCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetDeadCode',
            analysis__pb2.FileRequest.SerializeToString,
            analysis__pb2.DeadCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetCallGraph',
            analysis__pb2.FileRequest.SerializeToString,
            analysis__pb2.CallGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetDependencies',
            analysis__pb2.FileRequest.SerializeToString,
            analysis__pb2.DependencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImpact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetImpact',
            analysis__pb2.ImpactRequest.SerializeToString,
            analysis__pb2.ImpactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetFullAnalysis',
            analysis__pb2.EmptyRequest.SerializeToString,
            analysis__pb2.FullAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrackedFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetTrackedFiles',
            analysis__pb2.EmptyRequest.SerializeToString,
            analysis__pb2.TrackedFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/HealthCheck',
            analysis__pb2.EmptyRequest.SerializeToString,
            analysis__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
